# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'STT_ui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(787, 714)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 31, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.recordLabel = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.recordLabel.setFont(font)
        self.recordLabel.setObjectName("recordLabel")
        self.horizontalLayout.addWidget(self.recordLabel)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.languageLabel = QtWidgets.QLabel(Dialog)
        self.languageLabel.setObjectName("languageLabel")
        self.verticalLayout.addWidget(self.languageLabel)
        self.German_tick = QtWidgets.QRadioButton(Dialog)
        self.German_tick.setObjectName("German_tick")
        self.verticalLayout.addWidget(self.German_tick)
        self.Turkish_tick = QtWidgets.QRadioButton(Dialog)
        self.Turkish_tick.setObjectName("Turkish_tick")
        self.verticalLayout.addWidget(self.Turkish_tick)
        self.Polish_tick = QtWidgets.QRadioButton(Dialog)
        self.Polish_tick.setObjectName("Polish_tick")
        self.verticalLayout.addWidget(self.Polish_tick)
        self.Spanish_tick = QtWidgets.QRadioButton(Dialog)
        self.Spanish_tick.setObjectName("Spanish_tick")
        self.verticalLayout.addWidget(self.Spanish_tick)
        self.English_tick = QtWidgets.QRadioButton(Dialog)
        self.English_tick.setObjectName("English_tick")
        self.verticalLayout.addWidget(self.English_tick)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setText("")
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setPixmap(QtGui.QPixmap("logo.jpg"))
        self.label.setScaledContents(True)
        self.label.setWordWrap(False)
        self.label.setOpenExternalLinks(True)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.recordButton = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.recordButton.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../record-icon-14-256.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.recordButton.setIcon(icon)
        self.recordButton.setDefault(False)
        self.recordButton.setFlat(False)
        self.recordButton.setObjectName("recordButton")
        self.horizontalLayout_2.addWidget(self.recordButton)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        spacerItem5 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem5)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Speech to text"))
        self.recordLabel.setText(_translate("Dialog", "Click the button to record your speech:"))
        self.languageLabel.setText(_translate("Dialog", "Language:"))
        self.German_tick.setText(_translate("Dialog", "German"))
        self.Turkish_tick.setText(_translate("Dialog", "Turkish"))
        self.Polish_tick.setText(_translate("Dialog", "Polish"))
        self.Spanish_tick.setText(_translate("Dialog", "Spanish"))
        self.English_tick.setText(_translate("Dialog", "English"))
        self.recordButton.setText(_translate("Dialog", "Record"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

